// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rookie.BackendAPI.Data;

namespace Rookie.BackendAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasColumnType("ntext")
                        .HasColumnName("description");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = "C3001",
                            CategoryName = "Vegatables",
                            Description = "Vegetables are parts of plants that are consumed by humans or other animals as food",
                            IsDelete = false
                        },
                        new
                        {
                            CategoryId = "C3002",
                            CategoryName = "Fruits",
                            Description = "a fruit is the seed-bearing structure in flowering plants that is formed from the ovary after flowering",
                            IsDelete = false
                        },
                        new
                        {
                            CategoryId = "C3003",
                            CategoryName = "Juice",
                            Description = "Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables",
                            IsDelete = false
                        },
                        new
                        {
                            CategoryId = "C3004",
                            CategoryName = "Dried",
                            Description = "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators",
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Image", b =>
                {
                    b.Property<string>("ImageID")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("image_id");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_01");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_02");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_03");

                    b.Property<string>("Image4")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_04");

                    b.Property<string>("Image5")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_05");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ImageID");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ImageID = "I2001",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4001"
                        },
                        new
                        {
                            ImageID = "I2002",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4002"
                        },
                        new
                        {
                            ImageID = "I2003",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4003"
                        },
                        new
                        {
                            ImageID = "I2004",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4004"
                        },
                        new
                        {
                            ImageID = "I2005",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4005"
                        },
                        new
                        {
                            ImageID = "I2006",
                            Image1 = "/images/product-8.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4006"
                        },
                        new
                        {
                            ImageID = "I2007",
                            Image1 = "/images/product-3.jpg",
                            Image2 = "/images/product-7.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4007"
                        },
                        new
                        {
                            ImageID = "I2008",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4008"
                        },
                        new
                        {
                            ImageID = "I2009",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-4.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4009"
                        },
                        new
                        {
                            ImageID = "I2010",
                            Image1 = "/images/product-1.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4010"
                        },
                        new
                        {
                            ImageID = "I2011",
                            Image1 = "/images/product-4.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4011"
                        },
                        new
                        {
                            ImageID = "I2012",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-5.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4012"
                        },
                        new
                        {
                            ImageID = "I2013",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-7.jpg",
                            ProductId = "P4013"
                        },
                        new
                        {
                            ImageID = "I2014",
                            Image1 = "/images/product-11.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4014"
                        },
                        new
                        {
                            ImageID = "I2015",
                            Image1 = "/images/product-1.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4015"
                        },
                        new
                        {
                            ImageID = "I2016",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4016"
                        },
                        new
                        {
                            ImageID = "I2017",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4017"
                        },
                        new
                        {
                            ImageID = "I2018",
                            Image1 = "/images/product-1.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4018"
                        },
                        new
                        {
                            ImageID = "I2019",
                            Image1 = "/images/product-1.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4019"
                        },
                        new
                        {
                            ImageID = "I2020",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4020"
                        },
                        new
                        {
                            ImageID = "I2021",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4021"
                        },
                        new
                        {
                            ImageID = "I2022",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4022"
                        },
                        new
                        {
                            ImageID = "I2023",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4023"
                        },
                        new
                        {
                            ImageID = "I2024",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4024"
                        },
                        new
                        {
                            ImageID = "I2025",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4025"
                        },
                        new
                        {
                            ImageID = "I2026",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4026"
                        },
                        new
                        {
                            ImageID = "I2027",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4027"
                        },
                        new
                        {
                            ImageID = "I2028",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-7.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4028"
                        },
                        new
                        {
                            ImageID = "I2029",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-7.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4029"
                        },
                        new
                        {
                            ImageID = "I2030",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-7.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4030"
                        },
                        new
                        {
                            ImageID = "I2031",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-7.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4031"
                        },
                        new
                        {
                            ImageID = "I2032",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-7.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4032"
                        },
                        new
                        {
                            ImageID = "I2033",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4033"
                        },
                        new
                        {
                            ImageID = "I2034",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4034"
                        },
                        new
                        {
                            ImageID = "I2035",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4035"
                        },
                        new
                        {
                            ImageID = "I2036",
                            Image1 = "/images/product-5.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4036"
                        },
                        new
                        {
                            ImageID = "I2037",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4037"
                        },
                        new
                        {
                            ImageID = "I2038",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4038"
                        },
                        new
                        {
                            ImageID = "I2039",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4039"
                        },
                        new
                        {
                            ImageID = "I2040",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4040"
                        },
                        new
                        {
                            ImageID = "I2041",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4041"
                        },
                        new
                        {
                            ImageID = "I2042",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4042"
                        },
                        new
                        {
                            ImageID = "I2043",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4043"
                        },
                        new
                        {
                            ImageID = "I2044",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4044"
                        },
                        new
                        {
                            ImageID = "I2045",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4045"
                        },
                        new
                        {
                            ImageID = "I2046",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4046"
                        },
                        new
                        {
                            ImageID = "I2047",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4047"
                        },
                        new
                        {
                            ImageID = "I2048",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4048"
                        },
                        new
                        {
                            ImageID = "I2049",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4049"
                        },
                        new
                        {
                            ImageID = "I2050",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4050"
                        },
                        new
                        {
                            ImageID = "I2051",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4051"
                        },
                        new
                        {
                            ImageID = "I2052",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4052"
                        },
                        new
                        {
                            ImageID = "I2053",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4053"
                        },
                        new
                        {
                            ImageID = "I2054",
                            Image1 = "/images/product-10.jpg",
                            Image2 = "/images/product-3.jpg",
                            Image3 = "/images/product-6.jpg",
                            ProductId = "P4054"
                        });
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("product_id");

                    b.Property<string>("CateId")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("manufacturing_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.HasKey("ProductId");

                    b.HasIndex("CateId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = "P4001",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 32m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4002",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24m,
                            ProductName = "Ginger"
                        },
                        new
                        {
                            ProductId = "P4003",
                            CateId = "C3004",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30m,
                            ProductName = "Celery"
                        },
                        new
                        {
                            ProductId = "P4004",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4005",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 32m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4006",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24m,
                            ProductName = "Ginger"
                        },
                        new
                        {
                            ProductId = "P4007",
                            CateId = "C3004",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30m,
                            ProductName = "Celery"
                        },
                        new
                        {
                            ProductId = "P4008",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4009",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 32m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4010",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24m,
                            ProductName = "Ginger"
                        },
                        new
                        {
                            ProductId = "P4011",
                            CateId = "C3004",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30m,
                            ProductName = "Celery"
                        },
                        new
                        {
                            ProductId = "P4012",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4013",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 32m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4014",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24m,
                            ProductName = "Ginger"
                        },
                        new
                        {
                            ProductId = "P4015",
                            CateId = "C3004",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30m,
                            ProductName = "Celery"
                        },
                        new
                        {
                            ProductId = "P4016",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4017",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 32m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4018",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24m,
                            ProductName = "Ginger"
                        },
                        new
                        {
                            ProductId = "P4019",
                            CateId = "C3004",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30m,
                            ProductName = "Celery"
                        },
                        new
                        {
                            ProductId = "P4020",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4021",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4022",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4023",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4024",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4025",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4026",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4027",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4028",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4029",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4030",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4031",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4032",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4033",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4034",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4035",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4036",
                            CateId = "C3001",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50m,
                            ProductName = "Tomato"
                        },
                        new
                        {
                            ProductId = "P4037",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4038",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4039",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4040",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4041",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4042",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4043",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4044",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4045",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4046",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4047",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4048",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4049",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4050",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4051",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4052",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4053",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        },
                        new
                        {
                            ProductId = "P4054",
                            CateId = "C3002",
                            Description = "Vegetable is very healthy",
                            ExpiryDate = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ManufacturingDate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 48m,
                            ProductName = "Apple"
                        });
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Rating", b =>
                {
                    b.Property<string>("RateId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rate_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RateNumber")
                        .HasColumnType("int")
                        .HasColumnName("rate_number");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("RateId");

                    b.HasIndex("ProductId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            RateId = "R1001",
                            ProductId = "P4004",
                            RateNumber = 0
                        });
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Rookie.BackendAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Rookie.BackendAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rookie.BackendAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Rookie.BackendAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Image", b =>
                {
                    b.HasOne("Rookie.BackendAPI.Models.Product", "Product")
                        .WithOne("Image")
                        .HasForeignKey("Rookie.BackendAPI.Models.Image", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Product", b =>
                {
                    b.HasOne("Rookie.BackendAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Rating", b =>
                {
                    b.HasOne("Rookie.BackendAPI.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Rookie.BackendAPI.Models.Product", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
